services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  ml_client:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
    container_name: ml_client
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/containerapp
    ports:
      - "5000:5000"
    networks:
      - app_network
    volumes:
      - ml_data:/app/data

  web_app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - ml_client
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/containerapp
      - ML_CLIENT_URI=http://ml_client:5000
    networks:
      - app_network
    volumes:
      - web_data:/app/static

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
  ml_data:
  web_data:
